# Deploy static content to GitHub Pages
name: Deploy Pages
on:
  push:
    branches: ['main']
    paths: ['test/html/**']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read    # to read repository content
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './test/html'
      - uses: actions/deploy-pages@v4
        id: deployment
